import { StudentProfile } from "../types";

export const DEFAULT_STUDENT_PROFILE: StudentProfile = {
  name: "",
  college: "",
  degree: "",
  branch: "",
  year: "",
  gpa: "",
  backlogs: "None",
  location: "",
  preferredLocation: "",
  technicalSkills: [],
  nonTechnicalSkills: [],
  projects: "",
  internships: "",
  certifications: "",
  extracurriculars: "",
  communicationLevel: "Beginner",
  careerGoals: "",
  targetRoles: [],
  targetCompanies: [],
  salaryExpectation: "",
  workMode: "Hybrid / Remote",
  timeAvailable: "",
  placementDeadline: "",
  resumeStatus: "None",
  linkedInStatus: "None",
  portfolioStatus: "None",
  codingLevel: "Beginner",
  confidenceLevel: "Medium",
  constraints: "",
  linkedinUrl: "",
  githubUrl: "",
  email: "",
  phone: "",
  vorynexaId: "VNX-DEMO88"
};
